CREATE TABLE T_K_MOTTAKER_ID_TYPE       --???????
(
    K_MOTTAKER_ID_TYPE  VARCHAR(20) NOT NULL,

    PRIMARY KEY (K_MOTTAKER_ID_TYPE)
);

CREATE TABLE T_K_STATUS
(
    K_STATUS  VARCHAR(20) NOT NULL,

    PRIMARY KEY (K_STATUS)
);

CREATE TABLE T_K_KANAL
(
    K_KANAL  VARCHAR(20) NOT NULL,

    PRIMARY KEY (K_KANAL)
);

INSERT INTO T_K_MOTTAKER_ID_TYPE(K_MOTTAKER_ID_TYPE) VALUES ('FNR');

INSERT INTO T_K_STATUS(K_STATUS) VALUES ('OPPRETTET');
INSERT INTO T_K_STATUS(K_STATUS) VALUES ('OVERSENDT');
INSERT INTO T_K_STATUS(K_STATUS) VALUES ('FERDIGSTILT');
INSERT INTO T_K_STATUS(K_STATUS) VALUES ('FEILET');

INSERT INTO T_K_KANAL(K_KANAL) VALUES ('SMS');
INSERT INTO T_K_KANAL(K_KANAL) VALUES ('EPOST');