ALTER TABLE T_NOTIFIKASJON_DISTRIBUSJON ALTER COLUMN TITTEL TYPE VARCHAR(100);
ALTER TABLE T_NOTIFIKASJON_DISTRIBUSJON ALTER COLUMN OPPRETTET_AV TYPE VARCHAR(100);
ALTER TABLE T_NOTIFIKASJON_DISTRIBUSJON ALTER COLUMN ENDRET_AV TYPE VARCHAR(100);

ALTER TABLE T_NOTIFIKASJON ALTER COLUMN BESTILLINGS_ID TYPE VARCHAR(100);
ALTER TABLE T_NOTIFIKASJON ALTER COLUMN BESTILLER_ID TYPE VARCHAR(100);
ALTER TABLE T_NOTIFIKASJON ALTER COLUMN OPPRETTET_AV TYPE VARCHAR(100);
ALTER TABLE T_NOTIFIKASJON ALTER COLUMN ENDRET_AV TYPE VARCHAR(100);
