kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: doknotifikasjon
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DOKNOTIFIKASJON_TMP
      value: {{ DOKNOTIFIKASJON_TMP }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKNOTIFIKASJON }}
        mountPath: /var/run/secrets/nais.io/srvdoknotifikasjon
      - kvPath: {{ VAULT }}
        mountPath: /var/run/secrets/nais.io/vault