kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: doknotifikasjon
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DKIF_URL
      value: {{ DKIF_URL }}
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: SECURITY_TOKEN_SERVICE_SAML_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_SAML_TOKEN_URL }}
    - name: SIKKERHETSNIVAA_V1_URL
      value: {{ SIKKERHETSNIVAA_V1_URL }}
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: {{ SPRING_KAFKA_BOOTSTRAP_SERVERS }}
    - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
      value: {{ SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL }}
    - name: MOUNT_PATH
      value: {{ MOUNT_PATH }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  image: {{ image }}
  leaderElection: true
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKNOTIFIKASJON }}
        mountPath: /var/run/secrets/nais.io/srvdoknotifikasjon
      - kvPath: {{ VAULT }}
        mountPath: /var/run/secrets/nais.io/vault