###############################################
#                    KAFKA                    #
###############################################
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.schema.registry.url=http://127.0.0.1:8081
spring.kafka.bootstrap-servers=SASL_PLAINTEXT://127.0.0.1:9092
spring.kafka.properties.sasl.jaas.config=
server.port=8888

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.driverClassName=org.postgresql.Driver